version: "3"

services:
  backend:
    build:
      context: ./galva-be
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    restart: always
    networks:
      - network-backend
      - network-frontend

  frontend:
    depends_on:
      - backend
    restart: always
    build:
      context: ./galva-fe
      dockerfile: Dockerfile
    ports:
      - 3000:80
    networks:
      - network-frontend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - network-backend
      - network-frontend


networks:
  network-backend: {}
  network-frontend: {}