version: "3.8"

services:
  backend:
    build:
      context: ./galva-be
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    restart: always
    networks:
      - galva-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    build:
      context: ./galva-fe
      dockerfile: Dockerfile
    networks:
      - galva-network

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - galva-network

networks:
  galva-network:
    driver: bridge
